name: deploy

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            username: ${{ secrets.USER  }}
            password: ${{ secrets.PASSWD  }}


        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            tags: |
              type=semver,pattern={{version}}

            
        - name: Build and push Docker images
          uses: docker/build-push-action@v6.9.0
          with:
            push: true
            context: .
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
