name: deploy

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            username: ${{ secrets.USER  }}
            password: ${{ secrets.PASSWD  }}
        
        - name: Build and push Docker images
          uses: docker/build-push-action@v6.9.0
          with:
            push: true
            context: .
            tags: |
              rtpragana/estudo:${{ github.ref }}
